---
- name: Create Docker Image
  hosts: all
  become: yes
  tasks:

    - name: Copy Dockerfile to the remote host
      copy:
        src: Dockerfile
        dest: /home/dldperez/Dockerfile

    - name: copy static web page app files to remote hosts
      copy:
        src: ./front-end
        dest: /home/dldperez/front-end
        remote_src: no

    - name: Build Docker Image
      command:
        cmd: docker build -t webapp .
        chdir: /home/dldperez
      become: true

