---
- name: Configure Nginx Server
  hosts: all
  become: true
  tasks:

    - name: Ensure that /etc/ngix/conf.d exists
      file:
        path: /etc/nginx/conf.d
        state: directory

#this is to ensure that the html files is run
# not the default index.html(see the default.conf.2 for more details)

    - name: Copy nginx default.conf
      template:
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state:  restarted


